title: SungJin Kang blog
author: SungJin Kang
email: hour30000@gmail.com
description: about programming, game development
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: SungJin Kang
  tagline: Programmer
  date_format: "%b %-d, %Y"
  disqus_shortname: sungjinkangblog
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/logo.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "kr" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: #https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    #- home
    - page
    - post
  # generate social links in footer
  social_links:
    #twitter: SungJinKang6
    github:  SungJJinKang
    #linkedIn: in/samarsault
    #rss: rss
    #dribbble: jekyll
    #flickr:   jekyll
    #instagram: jekyll
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll
    #email: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed


url: "https://sungjjinkang.github.io" # the base hostname & protocol for your site

highlighter: rouge

